backends:
  - name: "test.home"
    location: "127.0.0.1:8000"
  - name: "test2.home"
    location: "127.0.0.1:8000"
  - name: "pihole.home"
    location: "192.168.1.250"

tls:
  key_path: "certs/key"
  cert_path: "certs/cert.crt"