listen:
  address: [127, 0, 0, 1]
  port: 4000

tls:
  key_path: "../certs/key"
  cert_path: "../certs/cert.crt"

backends:
  - name: "test.home"
    location: "127.0.0.1:8000"
  - name: "test2.home"
    location: "127.0.0.1:8000"
  - name: "pihole.home"
    location: "192.168.1.250"
